name: Test Workflow
on:
  push:
    branches:
      - main

jobs:
  api_test:
    name: API Test
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Set up API Test environment
        run: |
          mkdir -p tests
          Copy-Item -Path API-reqres/Postman\ Collection/Reqres.json -Destination tests/Reqres.json
          Copy-Item -Path API-reqres/Postman\ Collection/api-environment.json -Destination tests/api-environment.json

      - name: Run API Test
        run: newman run tests/Postman Collections/Reqres.json -e tests/Postman Collections/Reqres.in.postman_environment.json.json

      - name: Save Newman Report
        run: |
          mkdir -p test-results
          cp newman/*.html test-results/

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: API Test Results
          path: test-results/

